on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C5
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/mnist-sample.git
      url: context.event.github.url
      ref: context.event.github.ref
    outputs:
      repo:
        type: volume
  TrainModel:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      modelos:
        type: dataset
        with:
          ref: modelos-entrenados
    uses: script@v1
    with:
      script: |-
        pip install geffnet resnest pretrainedmodels albumentations opencv-python timm pytorch-model-summary wandb
        cp -R /inputs/repo /melanoma
        cd /melanoma
        python test.py
      image: pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime
